# -*- coding: utf-8 -*-
"""Untitled1643.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BCIRVke2XtFI1dLbLoIvXYe6ENgZKkSG
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
if not hasattr(np, 'PINF'):
    np.PINF = np.inf
if not hasattr(np, 'NINF'):
    np.NINF = -np.inf


try:
  import jax
except ModuleNotFoundError:
#   %pip install --upgrade "jax[cpu]"
# install commplax if not found
try:
  import commplax
except ModuleNotFoundError:
#   %pip install https://github.com/ChenHongBo0420/Comm/archive/master.zip
# install data api if not found
try:
  import labptptm1
except ModuleNotFoundError:
#   %pip install https://github.com/ChenHongBo0420/LabPtPTm1/archive/master.zip


# install GDBP if not found
try:
  import gdbp
except ModuleNotFoundError:
#   %pip install https://github.com/ChenHongBo0420/Q/archive/main.zip
# ===============================================================
# 0) 依赖 & 数据加载（和原脚本一致）
# ===============================================================
import numpy as np, jax, jax.numpy as jnp
from tqdm.auto import tqdm
from functools import partial
from gdbp.Singledata import load as gdat_load
from gdbp import SingleSOTA as gb
from commplax import comm, util

ds_train = gdat_load(1, -20, 1)[0]   # train
ds_test = gdat_load(1, -20, 1)[0]

# ===============================================================
# 1) 只构造 CDC  — 无 GDBP
# ===============================================================
def make_cdc(data, mode='train', steps=3,
             dtaps=271, rtaps=321):
    """返回一个 CDC 模型（ntaps=1, xi=0）"""
    fdbp_init  = partial(gb.fdbp_init, data.a, steps=steps)
    model_init = partial(gb.model_init, data)

    conf = dict(mode=mode, steps=steps,
                dtaps=dtaps, rtaps=rtaps,
                ntaps=1, init_fn=fdbp_init(xi=0.0))

    cdc = model_init(conf,               # 模型结构
                     sparams_flatkeys=[('fdbp_0',)],   # D-滤波固定
                     name='CDC')
    return cdc

model_tr = make_cdc(ds_train, mode='train')
model_te = make_cdc(ds_test,  mode='test')

# ===============================================================
# 2) 训练 CDC（500 iter）
# ===============================================================
buf = [None]*3
params = None
for _, p, _ in gb.train(model_tr, ds_train, n_iter=500):
    buf.append(p); params = buf.pop(0)   # 取第三近参数

# ===============================================================
# 3) 测试 CDC
# ===============================================================
metric, _ = gb.test(model_te, params, ds_test)
print(f"CDC   Q²={metric.QSq.total:6.2f} dB   BER={metric.BER.total:.3e}")

import zarr
import labptptm1.store as store   # 绝对导入，不用“.”
# 或者：
# from labptptm1 import store

root = store.open_group()
mods = list(root['815km_SSMF'].keys())
print("可用的 modulation formats：", mods)

import zarr
import labptptm1.store as store

root = store.open_group()
band = root['815km_SSMF']

for fmt in band.keys():
    lp_keys = list(band[fmt].keys())
    print(f"{fmt!r} 下的 LP keys：{lp_keys}")